apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-extratrees-dep
  labels:
    app: worker-extratrees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-extratrees
  template:
    metadata:
      labels:
        app: worker-extratrees
    spec:
      containers:
      - name: worker-extratrees
        image: shobuxtreme/ensembler.worker:extratrees-l
        ports:
        - containerPort: 9000
        env:
        - name: SERVER_PORT
          value: "9000"
        - name: MODEL_NAME
          value: "ExtraT"  
        - name: RABBIT_HOST
          value: "rabbitmq-svc"    
        - name: ENSEMBLER_DATASVC_URL
          value: "datasvc-svc:9002"      
        args: ["--server.port=$(SERVER_PORT)",
          "--worker.model.name=$(MODEL_NAME)", 
          "--spring.rabbitmq.host=$(RABBIT_HOST)", 
          "--ensembler.datasvc.url=$(ENSEMBLER_DATASVC_URL)/"]